oauth2-proxy:
  configuration:
    cookieSecret: wquLuiPVJ2vVLgWlU8Vwxy6xXS5RLBxqwwkycyGST_I=
    # Expires: 7/26/2022
    clientSecret: uZJ8Q~kw9jsFryOoxolPnkTmBnEL__OAfqO~Yac1
    clientID: 2d66d1f3-867b-481c-b6ed-764efd4af6a8
  args:
    - --provider=azure
    - --oidc-issuer-url=https://sts.windows.net/9bdc7505-8e8f-4c10-94aa-c87e1bdf110a/
    - --email-domain=*
    - --http-address=0.0.0.0:4180
    - --azure-tenant=9bdc7505-8e8f-4c10-94aa-c87e1bdf110a
    - --pass-access-token=true
    - --set-xauthrequest=true
  ingress:
    enabled: true
    annotations:
       kubernetes.io/ingress.class: traefik
       traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hostname: oauth2-proxy.localhost
    tls: true