oauth2-proxy:
  configuration:
    cookieSecret: wquLuiPVJ2vVLgWlU8Vwxy6xXS5RLBxqwwkycyGST_I=
    clientSecret: uZJ8Q~kw9jsFryOoxolPnkTmBnEL__OAfqO~Yac1
    clientID: 9bdc7505-8e8f-4c10-94aa-c87e1bdf110a
  args:
    - --provider=azure
    - --oidc-issuer-url=https://sts.windows.net/9bdc7505-8e8f-4c10-94aa-c87e1bdf110a/
    - --email-domain=*
    - --http-address=0.0.0.0:4180
    - --azure-tenant=9bdc7505-8e8f-4c10-94aa-c87e1bdf110a
    - --pass-access-token=true
    - --resource=6dae42f8-4368-4678-94ff-3960e28e3630
    - --set-xauthrequest=true