oauth2-proxy:
  configuration:
    cookieSecret: wquLuiPVJ2vVLgWlU8Vwxy6xXS5RLBxqwwkycyGST_I=
    # Expires: 7/26/2022
    clientSecret: uZJ8Q~kw9jsFryOoxolPnkTmBnEL__OAfqO~Yac1
    clientID: 2d66d1f3-867b-481c-b6ed-764efd4af6a8
  args:
    - --http-address=0.0.0.0:4180
    - --provider=oidc
    - --cookie-domain=https://login.microsoftonline.com/v2.0/2d66d1f3-867b-481c-b6ed-764efd4af6a8
    - --email-domain=*
    - --oidc-issuer-url=https://login.microsoftonline.com/9bdc7505-8e8f-4c10-94aa-c87e1bdf110a/v2.0
    - --login-url=https://login.microsoftonline.com/9bdc7505-8e8f-4c10-94aa-c87e1bdf110a/v2.0/oauth2/authorize
    - --redeem-url=https://login.microsoftonline.com/9bdc7505-8e8f-4c10-94aa-c87e1bdf110a/v2.0/oauth2/token 
    - --oidc-jwks-url=https://login.microsoftonline.com/common/discovery/keys
    - --profile-url=https://graph.microsoft.com/v1.0/me
    - --scope=openid
  ingress:
    # TODO:
    enabled: false
    tls: true
    selfSigned: true
    annotations:
       kubernetes.io/ingress.class: traefik
       traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hostname: oauth2-proxy.localhost