oauth2-proxy:
  configuration:
    cookieSecret: wquLuiPVJ2vVLgWlU8Vwxy6xXS5RLBxqwwkycyGST_I=
    # the web app secret; Expires: 7/26/2022
    clientSecret: uZJ8Q~kw9jsFryOoxolPnkTmBnEL__OAfqO~Yac1
    # the web app application ID
    clientID: 2d66d1f3-867b-481c-b6ed-764efd4af6a8
  image:
    # https://github.com/oauth2-proxy/oauth2-proxy/issues/1666
    tag: 7.2.1-debian-10-r154
  args:
    - --http-address=0.0.0.0:4180
    - --provider=azure
    - --azure-tenant=9bdc7505-8e8f-4c10-94aa-c87e1bdf110a
    - --email-domain=*
    # it configures oauth2-proxy to extract user's email claim from id_token rather than querying Graph api.
    - --oidc-issuer-url=https://sts.windows.net/9bdc7505-8e8f-4c10-94aa-c87e1bdf110a/
    # passes access token to upstream via X-Forwarded-Access-Token header.
    - --pass-access-token=true
    # along with --pass-access-token this adds access token to X-Auth-Request-Access-Token header to the response
    - --set-xauthrequest=true
  ingress:
    # TODO:
    enabled: false
    tls: true
    selfSigned: true
    annotations:
       kubernetes.io/ingress.class: traefik
       traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hostname: oauth2-proxy.localhost