apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: auth-localhost
spec:
  commonName: auth.localhost.com
  secretName: auth-localhost
  dnsNames:
    - auth.localhost.com
  issuerRef:
    name: letsencrypt-traefik2
    kind: ClusterIssuer