apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: oauth2-proxy
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`oauth2-proxy.localhost`)
      priority: 10
      services:
        - name: oauth2-proxy
          port: 80
  tls:
    certResolver: default
