traefik:
  ingressRoute:
    dashboard:
      enabled: true
  providers:
    kubernetesIngress:
      publishedService:
        enabled: true
  ports:
    traefik:
      expose: true
  additionalArguments:
    - --global.checknewversion
    - --entrypoints.metrics.address=:9100/tcp
    - --entrypoints.traefik.address=:9000/tcp
    - --entrypoints.web.address=:8000/tcp
    - --entryPoints.web.forwardedHeaders.insecure
    - --entrypoints.websecure.address=:8443/tcp
    - --entryPoints.websecure.forwardedHeaders.insecure
    - --api.dashboard=true
    - --ping=true
    - --providers.kubernetescrd
    - --providers.kubernetesingress
    - --providers.kubernetesingress.ingressendpoint.publishedservice=traefik/traefik
    - --serverstransport.insecureskipverify=true
    - --certificatesResolvers.default.acme.dnsChallenge=true
    - --certificatesResolvers.default.acme.dnsChallenge.provider=cloudflare
    - --certificatesresolvers.default.acme.email=ymedlop@localhost
    - --certificatesresolvers.default.acme.storage=acme.json
    - --certificatesresolvers.default.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory