traefik:
  additionalArguments:
    - --api
    - --api.insecure
    - --api.dashboard=true
    - --accesslog
    - --global.checknewversion=true
    - --entryPoints.traefik.address=:8100
    - --entryPoints.web.address=:80
    - --entryPoints.websecure.address=:443
    # permanent redirecting of all requests on http (80) to https (443)
    - --entrypoints.web.http.redirections.entryPoint.to=websecure
    - --ping=true
    - --providers.kubernetescrd=true
    - --providers.kubernetesingress=true
    - --serversTransport.insecureSkipVerify=true
    - --log.level=DEBUG