traefik:
  image:
    name: traefik
    tag: "2.8.1"
  additionalArguments:
    - --global.checknewversion
    - --entryPoints.traefik.address=:9000/tcp
    - --entryPoints.web.address=:8000/tcp
    - --entryPoints.websecure.address=:8443/tcp
    - --api.dashboard=true
    - --ping=true
    - --providers.kubernetesingress
    - --api
    - --api.insecure=true
    - --log.level=DEBUG
