traefik:
  additionalArguments:
    - --global.checknewversion
    - --global.sendanonymoususage
    - --entryPoints.traefik.address=:9000/tcp
    - --entryPoints.web.address=:8000/tcp
    - --entryPoints.websecure.address=:8443/tcp
    - --api.dashboard=true
    - --ping=true
    - --providers.kubernetescrd=true
    - --providers.kubernetesingress=true
    - --api
    - --api.insecure=true
    - --serversTransport.insecureskipverify=true
    - --log.level=DEBUG
