apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-forward-auth
spec:
  forwardAuth:
    address: https://traefik-forward-auth.localhost/_oauth
    trustForwardHeader: true
    authResponseHeaders:
      - X-Forwarded-User