apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-forward-auth
spec:
  forwardAuth:
    address: http://traefik-forward-auth.localhost
    trustForwardHeader: true
    authResponseHeaders:
      - X-Forwarded-User