apiVersion: v1
kind: Secret
metadata:
  name: traefik-forward-auth-secrets
  labels:
    app: traefik-forward-auth
type: Opaque
data:
    # the web app application ID
  traefik-forward-auth-oidc-client-id: MmQ2NmQxZjMtODY3Yi00ODFjLWI2ZWQtNzY0ZWZkNGFmNmE4
  # the web app secret; Expires: 7/26/2022
  traefik-forward-auth-oidc-client-secret: dVpKOFF+a3c5anNGcnlPb3hvbFBua1RtQm5FTF9fT0FmcU9+WWFjMQ==
  traefik-forward-auth-secret: wquLuiPVJ2vVLgWlU8Vwxy6xXS5RLBxqwwkycyGST_I=